import { useRef } from 'react'
import { FeaturedLighting } from './FeaturedLighting'
import { Bridge, SectionLabel } from './Circuit'
import { projects } from '../content/projects'
import { ProjectLinks } from './ProjectExplorer'
const caseCopy = {
  'circuit-minds': { title: 'A better place\nto learn.', label: 'FULL-STACK EDUCATION PLATFORM', problem: 'Learning is a connected experience. The software supporting it should be, too.', approach: 'Built separate public, portal, and API applications around a shared data model. Connected course discovery, sessions, enrollments, and authentication with Supabase and PostgreSQL.', result: 'An integrated platform spanning the interface, backend, and database—with practical debugging across each boundary.', lessons: 'The interesting work happens between layers: clear API contracts, consistent data, and predictable authentication.' },
  'voice-agent': { title: 'Testing the voice\non the other end.', label: 'REAL-TIME AI / CONVERSATION TESTING', problem: 'A voice agent needs to handle more than the happy path. Interruptions, unexpected inputs, and recovery matter.', approach: 'Connected Twilio phone calls to a FastAPI backend, WebSocket audio streams, and the OpenAI Realtime API. Exercised patient-style test conversations and failure scenarios.', result: 'A working call-testing workflow, supported by completed-call logs, backend evidence, and an example recording.', lessons: 'Real-time systems need careful attention to turn-taking, event ordering, and what happens when a conversation breaks down.' },
  'smart-house': { title: 'Small circuits.\nReal-world control.', label: 'EMBEDDED SYSTEMS / HOME AUTOMATION', problem: 'Physical systems need to respond reliably to a world that keeps changing.', approach: 'Integrated a PIC microcontroller, sensors, and custom circuits for entry access, day/night lighting, temperature-based control, and automated water flow.', result: 'A modular home-control project tested through repeated execution under different environmental conditions.', lessons: 'Reliable automation starts with understanding the sensor, the actuator, and the logic connecting them.' },
}
function VoiceVisual() {
  return <div className="voice-visual"><div className="mono visual-label"><i className="status-dot" /> Voice testing workflow</div><div className="audio-wave" aria-hidden="true">{Array.from({ length: 55 }, (_, i) => <i key={i} style={{ height: `${12 + Math.abs(Math.sin(i * 1.7) * Math.cos(i * 0.2)) * 115}px`, '--delay': `${i * -0.09}s` }} />)}</div><div className="voice-pipeline"><span>CALL</span><i>→</i><span>STREAM</span><i>→</i><span>RESPONSE</span></div><div className="voice-nodes"><span>Twilio</span><span>FastAPI</span><span>Realtime API</span></div><span className="mono visual-bottom">Listen. Interrupt. Recover.</span></div>
}
function HouseVisual() {
  return <div className="house-visual"><span className="mono visual-label">Smart home control</span><svg viewBox="0 0 600 350" aria-label="Sensors connected to a PIC controller and household outputs" role="img"><defs><linearGradient id="house-trace"><stop stopColor="#55dff5" /><stop offset="1" stopColor="#aa91ff" /></linearGradient></defs><g fill="none" stroke="url(#house-trace)" strokeWidth="1.5"><path d="M60 90H185L240 145M60 175H240M60 260H185L240 205M360 145L415 90H540M360 175H540M360 205L415 260H540" /><rect x="240" y="115" width="120" height="120" rx="12" /><rect x="250" y="125" width="100" height="100" rx="6" />{[90, 175, 260].map(y => <g key={y}><circle cx="60" cy={y} r="9" /><circle cx="540" cy={y} r="9" /></g>)}</g><g fill="#acb8cc" fontSize="22" fontFamily="sans-serif"><text x="25" y="65">LIGHT</text><text x="25" y="150">PRESENCE</text><text x="25" y="235">TEMPERATURE</text><text x="470" textAnchor="middle" y="65">LIGHTING</text><text x="470" textAnchor="middle" y="150">ACCESS</text><text x="470" textAnchor="middle" y="235">CLIMATE</text><text x="300" y="174" textAnchor="middle" fill="#55dff5" fontSize="30">PIC</text><text x="300" y="201" textAnchor="middle" fontSize="18">16F876A</text></g></svg><span className="mono visual-bottom">Sense → Process → Respond</span></div>
}
export function FeaturedProjects({ reduced }) {
  const root = useRef(null)
  return <section id="featured" className="featured section-shell" ref={root}><FeaturedLighting section={root} reduced={reduced} /><SectionLabel number="04">Featured projects</SectionLabel><div className="section-heading"><h2>Three projects.<br /><span>A closer look at my work.</span></h2></div>{projects.filter(p => p.featured).map((project, index) => {
    const copy = caseCopy[project.id]
    return <article id={`case-${project.id}`} className={`case-study case-${index}`} key={project.id}><span className="case-lamp-wash" aria-hidden="true" /><div className="case-meta mono"><span className="case-index">0{index + 1}</span><span>{copy.label}</span></div><div className="case-layout"><div className="case-visual">{index === 0 ? <div className="circuit-project-visual"><img src="/media/circuit-minds.webp" width="1400" height="933" alt="Circuit Minds platform overview illustration" loading="lazy" /><span className="mono">Website · Student portal · API</span></div> : index === 1 ? <VoiceVisual /> : <HouseVisual />}</div><div className="case-copy"><h3>{project.name}</h3><p className="case-subtitle">{project.summary}</p><div className="tags">{project.tech.map(t => <span key={t}>{t}</span>)}</div><ProjectLinks project={project} /></div></div><details className="case-details"><summary>Inside the project <span>+</span></summary><div className="case-deep"><div><h4>What I built</h4><p>{copy.approach}</p></div><div><h4>What it demonstrates</h4><p>{copy.result}</p></div><div><h4>What I took away</h4><p>{copy.lessons}</p></div></div>{index === 1 ? <div className="recording"><label htmlFor="voice-recording">Example test-call recording</label><audio id="voice-recording" controls preload="none" src="/media/voice-demo.mp3">Your browser does not support audio playback.</audio><a href="/media/voice-demo.mp3" download>Download recording ↓</a></div> : <a className="text-link" href={`/media/${project.image}.webp`} target="_blank" rel="noreferrer">View project overview image ↗</a>}</details></article>
  })}<Bridge label="BUILT ON A BROADER FOUNDATION" /></section>
}

