export const categories = [
  { id: 'software', name: 'Software Development', short: 'Software', index: '01', symbol: '⌘', description: 'Useful ideas, built end to end.', tags: 'Applications · Platforms · Games', image: 'circuit-minds' },
  { id: 'ai', name: 'AI & Machine Learning', short: 'Intelligence', index: '02', symbol: '⌁', description: 'Making data do something meaningful.', tags: 'Voice · Models · Prediction', image: 'skills-forecast' },
  { id: 'embedded', name: 'Embedded Systems & Robotics', short: 'Embedded', index: '03', symbol: '⊞', description: 'Where code meets the physical world.', tags: 'Sensors · Control · Robotics', image: 'smart-house' },
  { id: 'cloud', name: 'Cloud & Infrastructure', short: 'Infrastructure', index: '04', symbol: '▤', description: 'The systems that keep systems running.', tags: 'Linux · Cloud · Automation', image: 'infrastructure' },
]
export const projects = [
  { id: 'circuit-minds', category: 'software', name: 'Circuit Minds', summary: 'A full-stack education platform connecting a public website, student portal, and backend API.', tech: ['Next.js', 'NestJS', 'TypeScript', 'Supabase'], image: 'circuit-minds', repo: 'https://github.com/davidmtzh/circuit-minds', demo: 'https://circuit-minds-web.vercel.app/', featured: true, detail: 'Built course, session, and enrollment workflows across a multi-app monorepo. Integrated authentication and PostgreSQL-backed data with the frontend and API, then debugged routing, environment setup, and connectivity.' },
  { id: 'quintex', category: 'software', name: 'Quintex RPG', summary: 'A collaborative Unity RPG exploring real-time combat, puzzles, and sprite-based worlds.', tech: ['Unity', 'C#', 'Game systems'], image: 'quintex', repo: 'https://github.com/cmartinez1542/Quintex-RPG', demo: '#quintex', demoLabel: 'Discover the terminal', detail: 'A team project combining animation, combat scripting, dialogue, and quest systems. The repository includes Unity scenes and an Android build; the terminal below offers a separate browser scene preview.' },
  { id: 'portfolio', category: 'software', name: 'React Portfolio', summary: 'An earlier portfolio bringing technical projects, evidence, and résumé information together.', tech: ['React', 'JavaScript', 'Responsive UI'], repo: 'https://github.com/cmartinez1542/React-Portfolio', detail: 'The previous portfolio documented work across software, AI, electronics, and infrastructure. This new site reuses selected factual content and imagery, with an independent design and implementation.' },
  { id: 'voice-agent', category: 'ai', name: 'AI Voice Test Agent', summary: 'A real-time phone testing workflow for evaluating conversational healthcare agents.', tech: ['Python', 'FastAPI', 'Twilio', 'Realtime audio'], repo: 'https://github.com/davidmtzh/pgai-voice-challenge', featured: true, detail: 'Connected outbound phone calls, WebSocket audio streaming, and live AI responses. Evaluated interruptions, invalid inputs, conversation recovery, and call behavior. A technical testing project, not a clinical validation study.' },
  { id: 'skills', category: 'ai', name: 'Market Skills Forecasting', summary: 'Exploring technical skill demand through data preparation, feature engineering, and model evaluation.', tech: ['Python', 'Pandas', 'Scikit-learn'], image: 'skills-forecast', repo: 'https://github.com/davidmtzh/Forecasting-Future-Skills', detail: 'Prepared structured data, developed features, compared prediction approaches, and presented trends in a readable format.' },
  { id: 'azure-ml', category: 'ai', name: 'Azure ML · Model Comparison', summary: 'Comparing classification models on a public diabetes dataset.', tech: ['Azure ML', 'Classification', 'Evaluation'], detail: 'Configured a workspace and training jobs to compare logistic regression, random forest, and neural networks using accuracy and AUC. Documented in the résumé; no public demo is available.' },
  { id: 'house-prices', category: 'ai', name: 'House Price Prediction', summary: 'A regression experiment visualizing predicted house prices against observed values.', tech: ['Machine learning', 'Regression', 'Data visualization'], image: 'ml-house', detail: 'An existing project evaluation chart is retained as evidence. The source material does not establish enough methodology to make broader performance claims.' },
  { id: 'smart-house', category: 'embedded', name: 'Smart House Automation', summary: 'A PIC-based home control system connecting sensors to lighting, climate, access, and water control.', tech: ['PIC microcontroller', 'Assembly', 'Sensors'], image: 'smart-house', repo: 'https://github.com/davidmtzh/Embedded-Smart-Home-Control-System', featured: true, detail: 'Designed and tested multiple control modules, including smart key entry, day/night lighting, temperature-responsive climate control, and automated water flow. Validated behavior through repeated testing under changing conditions.' },
  { id: 'robotics', category: 'embedded', name: 'Autonomous Robotic Agent', summary: 'Sensor feedback and control logic for independent robot navigation.', tech: ['C++', 'Robotics', 'Control systems'], image: 'robotics', repo: 'https://github.com/davidmtzh/AI-Autonomous-Agent', detail: 'Integrated distance, proximity, and motion inputs with navigation logic. Refined behavior through iterative testing and debugging of hardware/software interfaces.' },
  { id: 'radio', category: 'embedded', name: 'Radio Transmitter & Receiver', summary: 'An analog breadboard prototype built and tuned through direct signal measurement.', tech: ['Analog electronics', 'Oscilloscope', 'Prototyping'], detail: 'Assembled a transmitter/receiver, adjusted component values, and used multimeters and oscilloscopes to inspect signal behavior. Documented in the systems engineering résumé.' },
  { id: 'linux', category: 'cloud', name: 'Distributed Linux Infrastructure', summary: 'A multi-VM environment with web, mail, DNS, authentication, and automation services.', tech: ['Linux', 'VMware', 'Kubernetes', 'Ansible'], image: 'infrastructure', repo: 'https://github.com/davidmtzh/Server-Deployment-Infrasructure', detail: 'Configured distributed services, automated administrative tasks, and investigated networking, authentication, and availability issues across Linux and Unix environments.' },
  { id: 'azure', category: 'cloud', name: 'Azure Deployment & CI/CD', summary: 'Deploying eShopOnWeb and building repeatable validation and delivery workflows.', tech: ['Azure', 'GitHub Actions', 'Azure DevOps', 'YAML'], image: 'azure-storefront', detail: 'Configured App Service deployment, resolved build/runtime failures, configured self-hosted agents, and applied pull-request build validation and branch policies. Includes storefront evidence from the original portfolio.' },
]
